name: DEPLOY
on:
  push:
    branches:
    - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Set Folder Ownership on EC2
      run: sudo chown -R www-data:www-data /var/www/html/my-book-mate
          
    - uses: actions/checkout@v3
    - name: rsync deployments
      uses: burnett01/rsync-deployments@7.0.1
      with:
        switches: -avzr --delete
        path: src/
        remote_path: ${{ secrets.TARGET_DIR }}
        remote_host: ${{ secrets.EC2_HOST }}
        remote_user: ${{ secrets.EC2_USERNAME }}
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
