name: Laravel Deployment to AWS EC2

on:
  push:
    branches:
      - master  # Updated to trigger on 'master' branch

jobs:
  deploy:
    name: Deploy Laravel to EC2
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 4: Sync files to EC2
      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # Private SSH key
          REMOTE_HOST: ${{ secrets.EC2_HOST }}             # Public EC2 IP or DNS
          REMOTE_USER: ${{ secrets.EC2_USERNAME }}         # EC2 user (e.g., ubuntu)
          TARGET: "${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/var/www/html/my-book-mate"            # Directory on EC2 instance

      # Step 5: Run Laravel Artisan Commands
      - name: Run Laravel Artisan Commands
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd /var/www/html/my-book-mate
          php artisan migrate --force
          php artisan cache:clear
          php artisan config:cache
          php artisan route:cache
          EOF
